1.Load the dataset from a CSV file named retail_data.csv.

2.Display the first 5 rows of the dataset.

3.Clean the data by removing any rows with missing values.

4.Create a new column named TotalPrice that is the product of Quantity and UnitPrice.

5.Group the data by Product Category and calculate the total TotalPrice for each Category.

6.Sort the resulting grouped data by TotalPrice in descending order and display the top 2 Categories.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\ritti\Downloads\retail_sales_dataset.csv")

In [3]:
df.head(5)

Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  24-11-2023     CUST001    Male   34           Beauty   
1               2  27-02-2023     CUST002  Female   26         Clothing   
2               3  13-01-2023     CUST003    Male   50      Electronics   
3               4  21-05-2023     CUST004    Male   37         Clothing   
4               5  06-05-2023     CUST005    Male   30           Beauty   

   Quantity  Price per Unit  
0         3            50.0  
1         2           500.0  
2         1            30.0  
3         1           500.0  
4         2            50.0

In [4]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              1
Age                 0
Product Category    2
Quantity            0
Price per Unit      1
dtype: int64

In [5]:
df.dropna(axis=0,inplace=True)

In [6]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
dtype: int64

In [7]:
df['Total price']=df['Quantity']*df['Price per Unit']

In [8]:
df

Transaction ID        Date Customer ID  Gender  Age Product Category  \
0                 1  24-11-2023     CUST001    Male   34           Beauty   
1                 2  27-02-2023     CUST002  Female   26         Clothing   
2                 3  13-01-2023     CUST003    Male   50      Electronics   
3                 4  21-05-2023     CUST004    Male   37         Clothing   
4                 5  06-05-2023     CUST005    Male   30           Beauty   
..              ...         ...         ...     ...  ...              ...   
995             996  16-05-2023     CUST996    Male   62         Clothing   
996             997  17-11-2023     CUST997    Male   52           Beauty   
997             998  29-10-2023     CUST998  Female   23           Beauty   
998             999  05-12-2023     CUST999  Female   36      Electronics   
999            1000  12-04-2023    CUST1000    Male   47      Electronics   

     Quantity  Price per Unit  Total price  
0           3            50.0        150.0  
1           2           500.0       1000.0  
2           1            30.0         30.0  
3           1           500.0        500.0  
4           2            50.0        100.0  
..        ...             ...          ...  
995         1            50.0         50.0  
996         3            30.0         90.0  
997         4            25.0        100.0  
998         3            50.0        150.0  
999         4            30.0        120.0  

[996 rows x 9 columns]

In [9]:
pdt_total=df.groupby("Product Category")['Total price'].sum().reset_index()

In [10]:
pdt_total

Product Category  Total price
0           Beauty     143515.0
1         Clothing     155360.0
2      Electronics     156205.0

In [11]:
pdt_total.sort_values(by="Total price", ascending=False).head(2)

Product Category  Total price
2      Electronics     156205.0
1         Clothing     155360.0

7.What is the difference between loc and iloc in Pandas?

In [12]:
# loc Select rows and columns by label
df.loc[0:5, ['Age', 'Quantity']]

Age  Quantity
0   34         3
1   26         2
2   50         1
3   37         1
4   30         2
5   45         1

In [13]:
# iloc Select rows and columns by integer position
df.iloc[0:5,[0,4]]

Transaction ID  Age
0               1   34
1               2   26
2               3   50
3               4   37
4               5   30

In [14]:
df.iloc[0:5,0:4]

Transaction ID        Date Customer ID  Gender
0               1  24-11-2023     CUST001    Male
1               2  27-02-2023     CUST002  Female
2               3  13-01-2023     CUST003    Male
3               4  21-05-2023     CUST004    Male
4               5  06-05-2023     CUST005    Male

8.merge two dataframe

In [15]:
# Creating two DataFrames
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})

In [16]:
df1

key  value
0   A      1
1   B      2
2   C      3

In [17]:
merge_df=pd.concat([df1,df2],axis=0,ignore_index=True)

In [18]:
merge_df

key  value
0   A      1
1   B      2
2   C      3
3   A      4
4   B      5
5   D      6

In [19]:
# Creating two DataFrames
df3 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value1': [1, 2, 3]})
df4 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value2': [4, 5, 6]})

In [20]:
# Merging DataFrames on the 'key' column
merged_df = pd.merge(df1, df2, on='key', how='inner')

In [21]:
merged_df

key  value_x  value_y
0   A        1        4
1   B        2        5

9.Fill na

In [28]:
df=pd.read_csv(r"C:\Users\ritti\Downloads\retail_sales_dataset.csv")

In [29]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              1
Age                 0
Product Category    2
Quantity            0
Price per Unit      1
dtype: int64

In [30]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)
df['Product Category'].fillna(df['Product Category'].mode()[0],inplace=True)
df['Price per Unit'].fillna(df['Price per Unit'].mean(),inplace=True)

In [31]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
dtype: int64

1.Create a 5×5 matrix with values ranging from 1 to 25.

2.Reshape the matrix to 1×25 and then back to 5×5.

3.Compute the sum of all elements in the matrix.

4.Calculate the mean of each row.

5.Replace all values greater than 10 with 10.

6.Transpose of the matrix.

In [32]:
import numpy as np

In [34]:
matrix=np.arange(1,26).reshape(5,5)

In [35]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
matrix=matrix.reshape(1,25)

In [39]:
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [46]:
matrix=matrix.reshape(5,5)

In [47]:
sum=np.sum(matrix)

In [48]:
sum

325

In [49]:
row_mean=np.mean(matrix,axis=1)

In [50]:
row_mean

array([ 3.,  8., 13., 18., 23.])

In [51]:
np.clip(matrix,a_min=None,a_max=10)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [52]:
np.transpose(matrix)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

7.matrix multiplication

In [54]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

In [55]:
result=np.dot(matrix1,matrix2)

In [56]:
result

array([[19, 22],
       [43, 50]])

In [57]:
result2=matrix1 @ matrix2

In [58]:
result2

array([[19, 22],
       [43, 50]])